import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Banner from "@/components/banner/Banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mutadeen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col`}
      >
        <div className="w-full border-2 border-green-800">
          <Header />
        </div>
        <main className="flex-1">{children}</main>

        <div className="flex flex-col items-center justify-center p-8 border-t border-gray-200 bg-3 text-gray-300">
          {/* Footer or additional content can go here */}
          <p>© 2025 Mutadeen. All rights reserved.</p>
        </div>
      </body>
    </html>
  );
}
