import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mutadeen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen min-h-full bg-white text-black`}
      >
        <div className="">
          <Header />
        </div>
        <div className="">{children}</div>

        <div className="flex flex-col items-center justify-center p-8 border-t border-gray-200 bg-3 text-gray-300">
          {/* Footer or additional content can go here */}
          <p>© 2025 Mutadeen. All rights reserved.</p>
        </div>
      </body>
    </html>
  );
}
